spring:
  cloud:
    application:
      name: assets-api
  redis:
    database: ${REDIS_DATABASE_INDEX:0}
    host: ${REDIS_HOST:172.19.255.201}
    port: ${REDIS_PORT:6379}
    timeout: ${REDIS_TIMEOUT:60000}
  cache:
    redis:
      time-to-live: ${CACHE_EXPIRATION:60000}
#  lifecycle:
#    timeout-per-shutdown-phase: 30s
info:
  app:
    name: spring-boot-k8s-demo
    description: Demo Spring boot and Kubernetes
management:
  endpoint:
    metrics:
      enabled: true
  endpoints:
    web:
      exposure:
        include: info,health,prometheus,metrics
  health:
    probes:
      enabled: true
server:
#  shutdown: graceful
  servlet:
    context-path: /api
feign.compression:
  request.enabled: true
  response.enabled: true
quote:
  url: 'https://mfinance.com.br/api/v1/stocks'
