apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: assets-app
  namespace: dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: assets-app
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: 95
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 200